[package]
name = "compressing_doubles"
version = "0.1.0"
authors = ["JakeHuneau <jakehuneau@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_streamer = "0.1.0"